// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PeriodicTable
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("appearance")]
        public string Appearance { get; set; }

        [JsonProperty("atomic_mass")]
        public double AtomicMass { get; set; }

        [JsonProperty("boil")]
        public double Boil { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("density")]
        public double Density { get; set; }

        [JsonProperty("discovered_by")]
        public string DiscoveredBy { get; set; }

        [JsonProperty("melt")]
        public double Melt { get; set; }

        [JsonProperty("molar_heat")]
        public double MolarHeat { get; set; }

        [JsonProperty("named_by")]
        public string NamedBy { get; set; }

        [JsonProperty("number")]
        public long Number { get; set; }

        [JsonProperty("period")]
        public long Period { get; set; }

        [JsonProperty("group")]
        public long Group { get; set; }

        [JsonProperty("phase")]
        public string Phase { get; set; }

        [JsonProperty("source")]
        public Uri Source { get; set; }

        [JsonProperty("summary")]
        public string Summary { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("xpos")]
        public long Xpos { get; set; }

        [JsonProperty("ypos")]
        public long Ypos { get; set; }

        [JsonProperty("wxpos")]
        public long Wxpos { get; set; }

        [JsonProperty("wypos")]
        public long Wypos { get; set; }

        [JsonProperty("shells")]
        public long[] Shells { get; set; }

        [JsonProperty("electron_configuration")]
        public string ElectronConfiguration { get; set; }

        [JsonProperty("electron_configuration_semantic")]
        public string ElectronConfigurationSemantic { get; set; }

        [JsonProperty("electron_affinity")]
        public double ElectronAffinity { get; set; }

        [JsonProperty("electronegativity_pauling")]
        public double ElectronegativityPauling { get; set; }

        [JsonProperty("ionization_energies")]
        public long[] IonizationEnergies { get; set; }

        [JsonProperty("cpk-hex")]
        public string CpkHex { get; set; }

        [JsonProperty("block")]
        public string Block { get; set; }
    }
}
